spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aktsoft
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: teja
    password: teja
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate: 
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect