 drop table if exists address;
 drop table if exists department;
 drop table if exists employee;
 drop table if exists employee_mission;
 drop table if exists mission;
 create table address (employee_id integer, id integer not null auto_increment, house_number varchar(255), street_name varchar(255), zip_code varchar(255), primary key (id));
 create table department (id integer not null auto_increment, name varchar(255), primary key (id));
 create table employee (address_id integer, date_of_birth date not null, department_id integer, id integer not null auto_increment, email varchar(255) not null, first_name varchar(255) not null, identifier varchar(255) not null, last_name varchar(255) not null, role enum ('ROLE_ADMIN','ROLE_USER') not null, primary key (id));
 create table employee_mission (employee_id integer not null, mission_id integer not null);
 create table mission (duration integer not null, id integer not null auto_increment, name varchar(255), primary key (id));
 alter table address add constraint UKpnjv1libu2pe8bpd4aeq55242 unique (employee_id);
 alter table employee add constraint UKqrbsk9ljmhfje93me0n7xwdxq unique (address_id);
 alter table employee add constraint UKfopic1oh5oln2khj8eat6ino0 unique (email);
 alter table employee add constraint UK5rh0wqupnwpehb050wgokpc4n unique (identifier);
 alter table address add constraint FKq4m60pqp7shng4u5n9h2346mp foreign key (employee_id) references employee (id);
 alter table employee add constraint FKga73hdtpb67twlr9c1i337tyt foreign key (address_id) references address (id);
 alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
 alter table employee_mission add constraint FKfgq6xw9slvmn8axdlck1asln7 foreign key (mission_id) references mission (id);
 alter table employee_mission add constraint FKn6kayjl3tuml7x7x79tgd5uiq foreign key (employee_id) references employee (id);